@host = http://127.0.0.1:3000
GET {{host}} HTTP/1.1

###
GET {{host}}/cursos HTTP/1.1
Accept: application/json

###
GET {{host}}/cursos/2 HTTP/1.1
Accept: application/json

###
POST {{host}}/cursos HTTP/1.1
Content-Type: application/json

{
    "id": 4,
    "nombre": "Algebra",
    "duracion": 10
}

###
PUT {{host}}/cursos/1 HTTP/1.1
Content-Type: application/json

{    
    "nombre": "Geometría",
    "duracion": 15
}