@host = http://127.0.0.1:3000
GET {{host}} HTTP/1.1

###
GET {{host}}/courses HTTP/1.1
Accept: application/json

###
GET {{host}}/courses/5 HTTP/1.1
Accept: application/json

###
POST {{host}}/courses HTTP/1.1
Content-Type: application/json

{
    "id": 3,
    "nombre": "Trigonometia",
    "duracion": 5
}

###
PUT {{host}}/courses/1 HTTP/1.1
Content-Type: application/json

{    
    "nombre": "Geometría",
    "duracion": 15
}

###
DELETE {{host}}/courses/3 HTTP/1.1
Content-Type: application/json